"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from poplib import CR

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ('couldbeanything123') 

# SECURITY WARNING: don't run with debug turned on in **production! 
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth', #authentication
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog.apps.BlogConfig', #blogapp
    'users.apps.UsersConfig', #usersapp
    'crispy_forms',  # crispy forms
    'crispy_bootstrap5',
    'debug_toolbar',
    'django_extensions'
]

UNFOLD = {
    "SITE_TITLE": "My Project Admin",
    "SITE_HEADER": "My Project",
    "SITE_SYMBOL": "dashboard",
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', #AuthenticationMiddleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'blog.middleware.ip_blacklist.IPBlacklistMiddleware',
    'users.middleware.DebugAuthMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CRISPY_ALLOWED_TEMPLATE_PACKS = ("bootstrap5",)
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_REDIRECT_URL = 'blog-home'
LOGIN_URL = 'login'

# LOGOUT_REDIRECT_URL = 'blog-home'
LOGOUT_REDIRECT_URL = 'logout-success'

# SENDING_EMAIL
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = '' 

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    # 1. FORMATTERS (Style)
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },

    # 2. HANDLERS (Destination)
    'handlers': {
        # Handler A: File mein save karega (Permanent record)
        'file': {
            'level': 'INFO',  # INFO aur usse upar sab file mein jayega
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
        # Handler B: Console pe dikhayega (Development ke liye)
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },

    # 3. LOGGERS (Trigger)
    'loggers': {
        # Django ke apne logs
        'django': {
            'handlers': ['file', 'console'], # Dono jagah bhejo
            'level': 'INFO',
            'propagate': True,
        },
        # Aapke blog app ke logs (e.g. blog.views)
        'myproject.blog': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,  # Root tak dobara mat bhejo (duplicate na ho)
        },
    },

    # Root logger taake aapke khud ke modules (jaise blog.views) bhi
    # `logging.getLogger(__name__)` se likhe gaye messages isi file mein aayein
    'root': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
    },
}

INTERNAL_IPS = ['127.0.0.1']
# BANNED_IPS = ['127.0.0.1']  #to check middleware 

SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_SECURE = True  #For production only
CSRF_COOKIE_SECURE = True